Lesson1 - Add directory with files
lyppay/wanacodee pull request #1
Opened 2024-09-18 13:28 UTC by lyppay

2024-09-18 15:22 UTC, mwanago commented on Lesson1_business-card/styles.css
> +    /* padding: 44px 206px 35px 19px; okomentowane bo chce o nie zapytac*/
Don't use Polish, even in the comments

2024-09-18 15:22 UTC, mwanago commented on Lesson1_business-card/styles.css
> +    /* padding: 29px 0px 29px 20px; okomentowane bo chce o nie zapytac*/
Don't use Polish, even in the comments

2024-09-18 15:23 UTC, mwanago commented on Lesson1_business-card/styles.css
> +} */
Please don't leave code that's commented like that

2024-09-18 15:23 UTC, mwanago commented on Lesson1_business-card/styles.css
> +.page{
There should be spaces before `{`

2024-09-30 14:26 UTC, Solnick requested changes
Please adjust your code to the comments made by @mwanago earlier

2024-09-30 14:30 UTC, lyppay commented on Lesson1_business-card/styles.css
> +.page{
line added

2024-09-30 14:31 UTC, lyppay commented on Lesson1_business-card/styles.css
> +} */
comment removed

2024-09-30 14:31 UTC, lyppay commented on Lesson1_business-card/styles.css
> +    /* padding: 29px 0px 29px 20px; okomentowane bo chce o nie zapytac*/
comment removed

2024-09-30 14:56 UTC, lyppay commented on Lesson1_business-card/styles.css
> +    /* padding: 44px 206px 35px 19px; okomentowane bo chce o nie zapytac*/
comment removed

2024-10-05 14:01 UTC, lyppay commented
> Please adjust your code to the comments made by @mwanago earlier

DONE

2024-10-05 14:36 UTC, lyppay commented on Lesson1_business-card/styles.css
> +.page{
fixed

2024-10-07 08:54 UTC, lyppay commented on Lesson1_business-card/styles.css
> +    /* padding: 44px 206px 35px 19px; okomentowane bo chce o nie zapytac*/
(I am resolving this, because conversation died)

2024-10-07 08:54 UTC, lyppay commented on Lesson1_business-card/styles.css
> +    /* padding: 29px 0px 29px 20px; okomentowane bo chce o nie zapytac*/
(I am resolving this, because conversation died)

2024-10-07 08:54 UTC, lyppay commented on Lesson1_business-card/styles.css
> +} */
(I am resolving this, because conversation died)

2024-10-07 08:54 UTC, lyppay commented on Lesson1_business-card/styles.css
> +.page{
(I am resolving this, because conversation died)

2024-10-07 08:55 UTC, merged

2024-10-07 08:55 UTC, lyppay commented
I have done merge to master because there was no action from long time

2024-10-08 13:33 UTC, Solnick commented on Lesson1_business-card/styles.css
> +    line-height: 35.16px;
don't use pixels with decimal points.

2024-10-08 13:33 UTC, Solnick commented on Lesson1_business-card/styles.css
> +    font-family: Roboto;
set the font for the whole body element. It should work and spare you setting the font-family in every text-element

2024-10-08 13:33 UTC, Solnick commented on Lesson1_business-card/styles.css
> +.street_txt, .email_txt, .phone_txt{
use kebab-case for class names

2024-10-09 15:39 UTC, lyppay commented on Lesson1_business-card/styles.css
> +    line-height: 35.16px;
done

2024-10-09 15:39 UTC, lyppay commented on Lesson1_business-card/styles.css
> +    font-family: Roboto;
done

2024-10-09 15:39 UTC, lyppay commented on Lesson1_business-card/styles.css
> +.street_txt, .email_txt, .phone_txt{
done
(kebab-case xDDDD)